# include: package:very_good_analysis/analysis_options.5.0.0.yaml
# linter:
#   rules:
#     public_member_api_docs: false

include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
