name: soccer_club_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  go_router: ^10.1.0
  intl: any

dev_dependencies:
  build_runner: 2.4.6
  device_preview: ^1.1.0
  lints: ^2.1.1
  flutter_gen_runner: any
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0
  widgetbook_generator: ^3.2.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          
