name: soccer_club_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.2
  dio: ^5.3.4
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  firebase_core: ^2.21.0
  video_player: ^2.8.1
  firebase_auth: ^4.12.1
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  go_router: ^10.1.0
  intl: any
  bloc: ^8.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: 2.4.6
  device_preview: ^1.1.0
  lints: ^2.1.1
  flutter_lints: ^2.0.3
  freezed: ^2.4.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
  widgetbook: ^3.3.0
  widgetbook_annotation: ^3.0.0
  widgetbook_generator: ^3.2.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
