// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9yxl_UPi_Lsdda067nDiUFY-ryvR-Jcs',
    appId: '1:532223591041:web:eacc3e4e428a4862944380',
    messagingSenderId: '532223591041',
    projectId: 'sporrt-club-app',
    authDomain: 'sporrt-club-app.firebaseapp.com',
    storageBucket: 'sporrt-club-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWvKbhHleRdcDqIPnoEpNJv70HWzCx46k',
    appId: '1:532223591041:android:ab2856730b3ddf87944380',
    messagingSenderId: '532223591041',
    projectId: 'sporrt-club-app',
    storageBucket: 'sporrt-club-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIIKIKn2jE33_QggnYGIrT_YUc8E2617w',
    appId: '1:532223591041:ios:cca9175df58759f6944380',
    messagingSenderId: '532223591041',
    projectId: 'sporrt-club-app',
    storageBucket: 'sporrt-club-app.appspot.com',
    iosBundleId: 'com.example.verygoodcore.soccer-club-app',
  );
}
